name: CombinedSlots
main: jasonwynn10\CrossOnlineCount\Main
version: 0.1.0
api: [3.9.3]
load: STARTUP
author: "jasonwynn10"
description: "A PocketMine plugin which checks other servers for online players and displays THE INFORMATIONvia slappers"
depend:
 - Slapper
